apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  storageClassName: ziosting-volume
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storageSize }}
