apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: web
  ports:
  - protocol: TCP
    name: http-svc
    port: {{ .Values.appPort }}
    targetPort: http
  